c = cvpartition(size(X,1),'kfold',k);
[coeff,soglie]=genera_rete(K,size(X,2));
net=struct('soglie',soglie,'coeff',coeff,'dimensione',K,'lambda',lambda);
generagrafo;
t1temp=0;t2temp=0;t3temp=0;NMSEtemp=[0,0,0];NSRtemp=[0,0,0];
for ii = 1:c.NumTestSets
    X_train=X(c.training(ii),:);
    Y_train=Y(c.training(ii),:);
    X_test=X(c.test(ii),:);
    Y_test=Y(c.test(ii),:);
    tic;
    batchsol=rvflreg(X_train,Y_train,net);
    t1temp=t1temp+toc;
    tic;
    distrsol=distributed_regression(X_train,Y_train,net,W,n_iter);
    t2temp=t2temp+toc;
    tic;
    [testNMSE,testNSR]=distributed_regressionsenzaconsensus(X_train,Y_train,X_test,Y_test,net,n_nodi);
    t3temp=t3temp+toc;
    [batcherr,batcherr2]=test_reg(X_test,Y_test,net,batchsol);
    [distrerr,distrerr2]=test_reg(X_test,Y_test,net,distrsol);
    NMSEtemp=NMSEtemp+[batcherr,distrerr,testNMSE];
    NSRtemp=NSRtemp+[batcherr2,distrerr2,testNSR];
    NMSE=NMSE+[batcherr,distrerr,testNMSE];
    NSR=NSR+[batcherr2,distrerr2,testNSR];
    te=te+[t1temp,t2temp,t3temp];
    fprintf('%i percento\n',((jj-1)*k+ii)*100/(k*n));
end
fprintf('Riepilogo run %i:\n---------------------------------------------------------------------------------------------------------------\n',jj);
fprintf('                                    Media NMSE:   Media NSR:   Media Training Time:\n\n');
fprintf('Dati non distribuiti:               %.4f        %.4f      %.4f\n\n',NMSEtemp(1)/k,NSRtemp(1)/k,t1temp/k);
fprintf('Dati distribuiti con consensus:     %.4f        %.4f      %.4f\n\n',NMSEtemp(2)/k,NSRtemp(2)/k,t2temp/k);
fprintf('Dati distribuiti senza consensus:   %.4f        %.4f      %.4f\n\n',NMSEtemp(3)/k,NSRtemp(3)/k,t3temp/k);